last_change = 2026-09-24T17:36:45.049824Z
addr = 0x14d6e0
size = 0x3
name = "IGameSystem_OnClientAdvanceNonRenderedFrame"

[header]
name = "IGameSystem_OnClientAdvanceNonRenderedFrame"
addr = 0x14d6e0

[header.args]
