last_change = 2026-09-24T17:36:45.049818Z
addr = 0x14d670
size = 0x3
name = "IGameSystem_OnClientPostAdvanceTick"

[header]
name = "IGameSystem_OnClientPostAdvanceTick"
addr = 0x14d670

[header.args]
