last_change = 2026-09-24T17:36:45.049868Z
addr = 0x9b1bd0
size = 0x56
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_CreateGameSystem"
type = "unsigned long long *"

[header]
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_CreateGameSystem"
addr = 0x9b1bd0
type = "unsigned long long *"

[header.args]
