last_change = 2026-09-24T17:36:45.049866Z
addr = 0x9b1b20
size = 0x5
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"
type = "char"

[header]
name = "CGameSystemReallocatingFactory_CSource2EntitySystem_Init"
addr = 0x9b1b20
type = "char"

[header.args]
