last_change = 2026-09-24T17:36:45.049873Z
addr = 0x9e09b0
size = 0x247
name = "CGameEventManager_FireEventClientSide"
type = "char"

[header]
name = "CGameEventManager_FireEventClientSide"
addr = 0x9e09b0
type = "char"

[header.args]
