last_change = 2026-09-24T17:36:45.049918Z
addr = 0xa4d5d0
size = 0x19
name = "CLoopModeGame_OnClientPreOutputParallelWithServer"
type = "long long"

[header]
name = "CLoopModeGame_OnClientPreOutputParallelWithServer"
addr = 0xa4d5d0
type = "long long"

[header.args]
