last_change = 2026-09-24T17:36:45.049908Z
addr = 0xa4d300
size = 0xd0
name = "CLoopModeGame_OnClientPollNetworking"
type = "long long"

[header]
name = "CLoopModeGame_OnClientPollNetworking"
addr = 0xa4d300
type = "long long"

[header.args]
