last_change = 2026-09-24T17:36:45.049910Z
addr = 0xa4d3d0
size = 0xd0
name = "CLoopModeGame_OnClientPostAdvanceTick"
type = "long long"

[header]
name = "CLoopModeGame_OnClientPostAdvanceTick"
addr = 0xa4d3d0
type = "long long"

[header.args]
