last_change = 2026-09-24T17:36:45.049906Z
addr = 0xa4d1f0
size = 0x103
name = "CLoopModeGame_OnClientPauseSimulate"
type = "long long"

[header]
name = "CLoopModeGame_OnClientPauseSimulate"
addr = 0xa4d1f0
type = "long long"

[header.args]
