last_change = 2026-09-24T17:36:45.049916Z
addr = 0xa4d5c0
size = 0xc
name = "CLoopModeGame_OnClientPreOutput"
type = "long long"

[header]
name = "CLoopModeGame_OnClientPreOutput"
addr = 0xa4d5c0
type = "long long"

[header.args]
