last_change = 2026-09-24T17:36:45.049922Z
addr = 0xa4d6d0
size = 0x38d
name = "CLoopModeGame_OnClientSimulate"
type = "long long"

[header]
name = "CLoopModeGame_OnClientSimulate"
addr = 0xa4d6d0
type = "long long"

[header.args]
