last_change = 2026-09-24T17:36:45.049902Z
addr = 0xa4d050
size = 0xd0
name = "CLoopModeGame_OnClientAdvanceTick"
type = "long long"

[header]
name = "CLoopModeGame_OnClientAdvanceTick"
addr = 0xa4d050
type = "long long"

[header.args]
