last_change = 2026-09-24T17:36:45.049912Z
addr = 0xa4d4a0
size = 0xc
name = "CLoopModeGame_OnClientPostOutput"
type = "long long"

[header]
name = "CLoopModeGame_OnClientPostOutput"
addr = 0xa4d4a0
type = "long long"

[header.args]
