last_change = 2026-09-24T17:37:01.469042Z
addr = 0xaaf2b0
size = 0x168
name = "CSimulationState_SetupJointState"
type = "double"

[header]
name = "CSimulationState_SetupJointState"
addr = 0xaaf2b0
type = "double"

[header.args]
