last_change = 2026-09-24T17:37:01.996377Z
addr = 0xb7a530
size = 0xbc
name = "CSource2Client_ProcessGameInput"
type = "long long"

[header]
name = "CSource2Client_ProcessGameInput"
addr = 0xb7a530
type = "long long"

[header.args]
