last_change = 2026-09-24T17:36:45.049981Z
addr = 0xc123c0
size = 0x1fb
name = "CViewRender_OnRenderStart"
type = "void *"

[header]
name = "CViewRender_OnRenderStart"
addr = 0xc123c0
type = "void *"

[header.args]
