last_change = 2026-09-24T17:37:02.364741Z
addr = 0xc35650
size = 0x300
name = "CMapAnNodeManager_FireGameEvent"
type = "long long"

[header]
name = "CMapAnNodeManager_FireGameEvent"
addr = 0xc35650
type = "long long"

[header.args]
