last_change = 2026-09-24T17:36:45.049988Z
addr = 0xd09b60
size = 0xb04
name = "ClientModeCSNormal_Update"
type = "long long"

[header]
name = "ClientModeCSNormal_Update"
addr = 0xd09b60
type = "long long"

[header.args]
