last_change = 2026-09-24T17:36:45.050001Z
addr = 0xf795f0
size = 0x5a
name = "GameStateAPI_BIsLocalServerHost"
type = "bool"

[header]
name = "GameStateAPI_BIsLocalServerHost"
addr = 0xf795f0
type = "bool"

[header.args]
