last_change = 2026-09-24T17:37:02.680826Z
addr = 0xf8bb30
size = 0x179
name = "GameStateAPI_GetAccoladeLocalizationString"
type = "char *"

[header]
name = "GameStateAPI_GetAccoladeLocalizationString"
addr = 0xf8bb30
type = "char *"

[header.args]
