last_change = 2026-09-24T17:36:45.050022Z
addr = 0xf8ffa0
size = 0x7
name = "GameStateAPI_GetCommendationTokensAvailable"
type = "long long"

[header]
name = "GameStateAPI_GetCommendationTokensAvailable"
addr = 0xf8ffa0
type = "long long"

[header.args]
