last_change = 2026-09-24T17:36:45.050024Z
addr = 0xf905e0
size = 0xa6
name = "GameStateAPI_GetCrosshairCode"
type = "char *"

[header]
name = "GameStateAPI_GetCrosshairCode"
addr = 0xf905e0
type = "char *"

[header.args]
