last_change = 2026-09-24T17:37:03.521588Z
addr = 0xf9d790
size = 0xf2
name = "GameStateAPI_GetLocalOrInEyePlayerXuid"
type = "char *"

[header]
name = "GameStateAPI_GetLocalOrInEyePlayerXuid"
addr = 0xf9d790
type = "char *"

[header.args]
