last_change = 2026-09-24T17:36:45.050094Z
addr = 0xfa82b0
size = 0xc3
name = "GameStateAPI_GetPlayerMoney"
type = "long long"

[header]
name = "GameStateAPI_GetPlayerMoney"
addr = 0xfa82b0
type = "long long"

[header.args]
