last_change = 2026-09-24T17:36:45.050140Z
addr = 0xfaa8d0
size = 0xa7
name = "GameStateAPI_GetPlayerXpTrailLevel"
type = "long long"

[header]
name = "GameStateAPI_GetPlayerXpTrailLevel"
addr = 0xfaa8d0
type = "long long"

[header.args]
