last_change = 2026-09-24T17:37:04.784737Z
addr = 0xfa7dc0
size = 0xd7
name = "GameStateAPI_GetPlayerDisplayFlairItem"
type = "char *"

[header]
name = "GameStateAPI_GetPlayerDisplayFlairItem"
addr = 0xfa7dc0
type = "char *"

[header.args]
