last_change = 2026-09-24T17:36:45.050044Z
addr = 0xfa0780
size = 0x44
name = "GameStateAPI_GetMapDisplayNameToken"
type = "void *"

[header]
name = "GameStateAPI_GetMapDisplayNameToken"
addr = 0xfa0780
type = "void *"

[header.args]
