last_change = 2026-09-24T17:37:03.890022Z
addr = 0xfa12c0
size = 0x3af
name = "GameStateAPI_GetMatchEndWinDataJSO"
type = "void"

[header]
name = "GameStateAPI_GetMatchEndWinDataJSO"
addr = 0xfa12c0
type = "void"

[header.args]
