last_change = 2026-09-24T17:36:45.050170Z
addr = 0xfb5a90
size = 0xd3
name = "GameStateAPI_HasCommunicationAbuseMute"
type = "bool"

[header]
name = "GameStateAPI_HasCommunicationAbuseMute"
addr = 0xfb5a90
type = "bool"

[header.args]
