last_change = 2026-09-24T17:36:45.050156Z
addr = 0xfb2760
size = 0x3a
name = "GameStateAPI_GetTeamLivingPlayerCount"
type = "long long"

[header]
name = "GameStateAPI_GetTeamLivingPlayerCount"
addr = 0xfb2760
type = "long long"

[header.args]
