last_change = 2026-09-24T17:36:45.050209Z
addr = 0xfc9150
size = 0x178
name = "GameStateAPI_IsReportCategoryEnabledForSelectedPlayer"
type = "bool"

[header]
name = "GameStateAPI_IsReportCategoryEnabledForSelectedPlayer"
addr = 0xfc9150
type = "bool"

[header.args]
