last_change = 2026-09-24T17:36:45.050203Z
addr = 0xfc8d70
size = 0xc8
name = "GameStateAPI_IsPlayerConnected"
type = "bool"

[header]
name = "GameStateAPI_IsPlayerConnected"
addr = 0xfc8d70
type = "bool"

[header.args]
