last_change = 2026-09-24T17:36:45.050247Z
addr = 0x15b0e00
size = 0x61e
name = "CEntitySystem_Init"
type = "long long"

[header]
name = "CEntitySystem_Init"
addr = 0x15b0e00
type = "long long"

[header.args]
